### ISSUE TITLE
No share replay button available

### ISSUE THREAD

**Issue by Jordan-Sage** [cpennington/dicedornot#11]
I know that it would be **REALLY** difficult to share a replay that was uploaded from file but if the source is a link it should be easier? Ones and Skulls has share feature (the long ass URL is hilarious) 

anyway, THANK YOU for this - it kicks ass

**Comment by cpennington** [comment]
Yeah, good call, a share link would be easy enough for link-based replays.

**Comment by cpennington** [comment]
Alright, this should be live soon. You'll need to reload a replay to get the sharing url.
