### ISSUE TITLE
Perpetual Loading

### ISSUE THREAD

**Issue by theamazingzorro** [cpennington/dicedornot#2]
Attempting to open this replay results in the website displaying the loading bar indefinitely. 

[Coach-327084-6c430b54ea3f0287e8136f5cf788a231_2020-05-22_23_28_44.zip](https://github.com/cpennington/dicedornot/files/4671161/Coach-327084-6c430b54ea3f0287e8136f5cf788a231_2020-05-22_23_28_44.zip)

**Comment by cpennington** [comment]
Hey, thanks for reporting this. I looked at it, and that file is  a zip file that contains a `.bbrz` (which is also a zip file, it turns out). DicedOrNot expects the raw `.bbrz` file, which is why it failed. We could definitely use better error messaging in this sort of case, though.

**Comment by theamazingzorro** [comment]
I only zipped the file so github would let me upload it, since github only supports the uploading of recognized file types. The file was not zipped when I first encountered this problem.
