### ISSUE TITLE
Error: Inconsistent values passed to SimpleDistribution. NaN != NaN when adding '7'

### ISSUE THREAD

**Issue by wagner-ch** [cpennington/dicedornot#44]
I tried to analyze a replay and got this error:

Error: Inconsistent values passed to SimpleDistribution. NaN != NaN when adding '7'

Ca/this.values<@https://dicedornot.vengefulpickle.com/dist/main.js:10:59563
Ca@https://dicedornot.vengefulpickle.com/dist/main.js:10:59495
get _possibleOutcomes@https://dicedornot.vengefulpickle.com/dist/main.js:11:41852
get possibleOutcomes@https://dicedornot.vengefulpickle.com/dist/main.js:11:26915
knockdownValue@https://dicedornot.vengefulpickle.com/dist/main.js:11:32093
failValue@https://dicedornot.vengefulpickle.com/dist/main.js:11:47156
get _possibleOutcomes/t<@https://dicedornot.vengefulpickle.com/dist/main.js:11:41397
get _possibleOutcomes@https://dicedornot.vengefulpickle.com/dist/main.js:11:41221
get possibleOutcomes@https://dicedornot.vengefulpickle.com/dist/main.js:11:26915
get _possibleOutcomes/t<@https://dicedornot.vengefulpickle.com/dist/main.js:11:41311
get _possibleOutcomes@https://dicedornot.vengefulpickle.com/dist/main.js:11:41221
get possibleOutcomes@https://dicedornot.vengefulpickle.com/dist/main.js:11:26915
get expectedValue@https://dicedornot.vengefulpickle.com/dist/main.js:11:26693
futurePlayerValue/r<@https://dicedornot.vengefulpickle.com/dist/main.js:11:33467
futurePlayerValue@https://dicedornot.vengefulpickle.com/dist/main.js:11:33453
get turnoverValue/e<@https://dicedornot.vengefulpickle.com/dist/main.js:11:33664
get turnoverValue@https://dicedornot.vengefulpickle.com/dist/main.js:11:33652
dieValue@https://dicedornot.vengefulpickle.com/dist/main.js:11:35805
value/r<@https://dicedornot.vengefulpickle.com/dist/main.js:11:37567
value@https://dicedornot.vengefulpickle.com/dist/main.js:11:37555
get actualValue@https://dicedornot.vengefulpickle.com/dist/main.js:11:27238
get valueWithDependents@https://dicedornot.vengefulpickle.com/dist/main.js:11:27333
Nw/s<@https://dicedornot.vengefulpickle.com/dist/main.js:11:62323
Nw@https://dicedornot.vengefulpickle.com/dist/main.js:11:62252
g/</<@https://dicedornot.vengefulpickle.com/dist/main.js:12:4516
xmlToJson/</</<@https://dicedornot.vengefulpickle.com/dist/main.js:10:3623

I think it's because the game ended with overtime? 
[Coach-334115-d60930c4007f715fdb609c3a5665f7ad_2021-04-14_19_01_24.zip](https://github.com/cpennington/dicedornot/files/6313669/Coach-334115-d60930c4007f715fdb609c3a5665f7ad_2021-04-14_19_01_24.zip)

**Comment by cale-at-reify** [comment]
This has been fixed.

**Comment by cpennington** [comment]
This has been fixed.
