### ISSUE TITLE
Issue with pile on players when injuring a player

### ISSUE THREAD

**Issue by Tom-Kennedy** [cpennington/dicedornot#5]
[Coach-62812-b437314ee8b26d0daddfa4d15095ea80_2020-11-06_18_24_36.txt](https://github.com/cpennington/dicedornot/files/5503735/Coach-62812-b437314ee8b26d0daddfa4d15095ea80_2020-11-06_18_24_36.txt)

Rename file to reproduce

**Comment by cpennington** [comment]
Should be fixed now.
