### ISSUE TITLE
Certain replays do not upload

### ISSUE THREAD

**Issue by JimmyDreambeard** [cpennington/dicedornot#6]
Hi, when I upload certain replays to the website, the site reports it is loading, but then stops. Not sure what is going on. Attached is a replay that doesn't upload .
https://drive.google.com/drive/folders/1gF7uKWCfz3BfFiPYSs1RWdsdXQmjV76g?usp=sharing

**Comment by cpennington** [comment]
This uses a Mixed team, which hasn't been implemented yet, so nothing shows up on the pitch.

**Comment by cpennington** [comment]
Fixed now
